#!/bin/bash
#Author: Kwame Fosu
#Date: 10/23/2022
#Description: Docker Installation
echo “Docker installation just started” 
curl -fsSL https://get.docker.com -o get-docker.sh
DRY_RUN=1 sudo sh ./get-docker.sh
echo “Docker installation completed successfully”


#!/bin/bash
#Author: Kwame Fosu
#Date: 10/23/2022
#Description: Installation of packages
echo “A list of packages will begin installing; this will take few minutes”
apt install wget -y 
apt install net-utils -y
apt install sysstat -y
apt install finger -y
apt install gcc -y
apt install make -y 
apt install python3 -y
apt install epel-release -y 
apt install git -y
apt install vim -y
echo “All packages installed successfully”

updating my scripts
